### ISSUE TITLE
Make Parser more intuitive

### ISSUE THREAD

**Issue by ischoegl** [microcombustion/ctwrap#35]
Currently `Parser` requires a list to to specify parameter values with dimensions and comments, i.e.
```yaml
    T: [300., kelvin, 'temperature']
    P: [1., atmosphere, 'pressure']
    phi: [.55, dimensionless, 'equivalence ratio']
    oxidizer: 'O2:1,AR:5'
```
It would be more intuitive to simply use a string and parse values using `re` from
```yaml
    T: 300. kelvin (temperature)
    P: 1. atmosphere (pressure)
    phi: .55 (equivalence ratio)
    oxidizer: O2:1,AR:5
```
