### ISSUE TITLE
Implement capability to restart simulations

### ISSUE THREAD

**Issue by ischoegl** [microcombustion/ctwrap#52]
For one-dimensional simulations, restarting from an adjacent solution can save significant time. One possible example would be:
```
strategy:
  matrix:
    upstream.phi: [0.5, 0.6, 0.7, 0.8]
    settings.transport: ['Mix', 'Multi']
```
where `Multi` could be restarted from `Mix`. For `Sobol` sequences, new points can be added based on triangulated initial guesses. 

**PS:** This is longer term and should not be considered for `0.2.0`
